# 左右通信の必須設定
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Macとの接続を最優先で安定させる設定
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_4=y

# スリープ設定（1時間）
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# 不要な機能と暴走している機能を完全にオフにする
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_STUDIO=n

CONFIG_ZMK_USB_LOGGING=y
