# 左右分割通信
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# 基本機能 ＆ ポインティング（スクロール/トラックボール）
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_KEYBOARD_NAME="Crosses"
CONFIG_ZMK_POINTING=y

# 電波出力を最大化 (+8dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 🛡️ 左右通信の安定化（左手の切断対策）
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION=y
