# 左右通信の必須設定
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# 【最重要】USB経由で内部ログ（デバッグ情報）を出力する設定
CONFIG_ZMK_USB_LOGGING=y

# スリープ設定（1時間）
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# 不要な機能のオフ
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_STUDIO=n
