manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Good-Great-Grand-Wonderful
      url-base: https://github.com/Good-Great-Grand-Wonderful
    - name: HeeTuic
      url-base: https://github.com/HeeTuic
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: cb-zmk-keebs
      remote: HeeTuic
      revision: main
      import: config/west.yml
  self:
    path: config
